"use strict";

const assert = require("node:assert/strict");
const crypto = require("node:crypto");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { spawnSync } = require("node:child_process");
const test = require("node:test");

const ROOT = path.resolve(__dirname, "..");
const read = relativePath => fs.readFileSync(path.join(ROOT, relativePath), "utf8");

test("generated root page is self-verifying and has no wall-clock build noise", () => {
  const indexSource = read("index.html");
  const marker = indexSource.match(
    /^<!doctype html>\n<!-- @generated by scripts\/build-index\.mjs; artifact-sha256=([a-f0-9]{64}); do not edit -->\n/
  );
  assert.ok(marker, "generated artifact marker is required");
  const normalizedBody = indexSource.replace(marker[0], "<!doctype html>\n");
  const artifactHash = crypto.createHash("sha256").update(normalizedBody).digest("hex");
  assert.equal(marker[1], artifactHash);
  assert.match(indexSource, /const EXPORTED_STATE_BLUEPRINT_SAVED_AT = "1970-01-01T00:00:00\.000Z";/);
  assert.equal((indexSource.match(/@generated by scripts\/build-index\.mjs/g) || []).length, 1);
});

test("public demo exposes only the qualified Managed Pilot offer", () => {
  const indexSource = read("index.html");
  const blueprintSource = indexSource.match(/const EXPORTED_STATE_BLUEPRINT = (\{.*\});/)?.[1];
  assert.ok(blueprintSource, "exported public blueprint is required");
  const model = JSON.parse(blueprintSource);
  const pricing = model.states.find(state => state.id === "site_pricing");
  const qualification = model.states.find(state => state.id === "site_checkout");
  const approach = model.states.find(state => state.id === "site_login");
  const acceptance = model.states.find(state => state.id === "site_profile");
  const home = model.states.find(state => state.id === "site_home");
  const publicModel = JSON.stringify(model);

  assert.deepEqual(pricing.data.plans.plans.map(plan => plan.title), ["Managed Pilot"]);
  assert.equal(pricing.data.plans.plans[0].price, "2.500–7.500 €");
  assert.equal(pricing.data.plans.plans[0].duration, "6–12 Wochen");
  assert.equal(qualification.data.qualification.prepared, false);
  assert.equal(approach.title, "Vorgehen");
  assert.equal(acceptance.title, "Abnahme");
  assert.equal(home.data.hero.actionLabel, "Editor öffnen");
  assert.equal(home.data.hero.url, "/state.html");
  assert.equal(home.data.hero.secondaryActionLabel, "Pilot ansehen");
  assert.equal(home.data.hero.secondaryTransitionId, "site_home_nav_pricing");
  assert.ok(!("order" in qualification.data));
  assert.ok(!("email" in approach.data.hero));
  assert.ok(!("password" in approach.data.hero));
  assert.ok(!("account" in acceptance.data));
  assert.doesNotMatch(publicModel, /(?:249|749|1\.990) EUR|\/Monat|Starter anfragen|Business anfragen|Scale anfragen|BI zubuchen/);
});

test("shipped preset images have no third-party runtime dependency", () => {
  assert.doesNotMatch(
    read("server/preset-catalog.js"),
    /(?:img\.daisyui\.com|images\.unsplash\.com|picsum\.photos)/
  );
});

test("release publication is manual, sequential, and gated by the reusable full CI", () => {
  const releaseWorkflow = read(".github/workflows/deploy.yml");
  const ciWorkflow = read(".github/workflows/ci.yml");
  const playwrightConfig = read("playwright.config.js");
  const packageJson = JSON.parse(read("package.json"));
  const triggerSection = releaseWorkflow.slice(0, releaseWorkflow.indexOf("jobs:"));

  assert.match(triggerSection, /workflow_dispatch:/);
  assert.doesNotMatch(triggerSection, /^\s*push:/m);
  assert.match(releaseWorkflow, /uses: \.\/\.github\/workflows\/ci\.yml/);
  assert.match(releaseWorkflow, /node scripts\/plan-managed-release\.mjs/);
  assert.match(releaseWorkflow, /RELEASE_MODE.*create/);
  assert.match(releaseWorkflow, /git push --atomic --force-with-lease/);
  assert.match(releaseWorkflow, /refs already published.*continuing/);
  assert.match(releaseWorkflow, /gh release view "\$RELEASE_ID"/);
  assert.match(releaseWorkflow, /GitHub release \$RELEASE_ID already exists; continuing/);
  assert.match(releaseWorkflow, /pages:[\s\S]*needs: deploy/);
  assert.match(releaseWorkflow, /git tag -a "\$RELEASE_ID"/);
  assert.match(releaseWorkflow, /actions\/upload-pages-artifact@v3/);
  assert.match(releaseWorkflow, /actions\/deploy-pages@v4/);
  assert.match(ciWorkflow, /pull_request:/);
  assert.match(ciWorkflow, /browser-contracts:/);
  assert.match(ciWorkflow, /webkit-smoke:/);
  assert.match(ciWorkflow, /npm audit --omit=dev --audit-level=high/);
  assert.match(ciWorkflow, /npm run check:workspace-core/);
  assert.match(ciWorkflow, /npm run check:index/);
  assert.match(ciWorkflow, /npm run test:server/);
  assert.match(ciWorkflow, /npm run test:browser -- --shard=\$\{\{ matrix\.shard \}\} --reporter=line,github/);
  assert.match(ciWorkflow, /npm run test:webkit/);
  assert.equal(
    packageJson.scripts["test:webkit"],
    "playwright test tests/webkit-product-smoke.spec.js --browser=webkit --workers=1 --reporter=list"
  );
  assert.match(playwrightConfig, /forbidOnly:\s*Boolean\(process\.env\.CI\)/);
});

test("static production artifact is an explicit allowlist", () => {
  const target = fs.mkdtempSync(path.join(os.tmpdir(), "digitalisierungsplanung-site-"));
  try {
    const result = spawnSync(process.execPath, [path.join(ROOT, "scripts/stage-static-site.mjs"), "--output", target], {
      cwd: ROOT,
      encoding: "utf8"
    });
    assert.equal(result.status, 0, result.stderr || result.stdout);
    assert.deepEqual(fs.readdirSync(target).sort(), [
      ".nojekyll",
      "CNAME",
      "assets",
      "disable-sw.js",
      "index.html",
      "manifest.webmanifest",
      "release-version.js",
      "state.html",
      "sw.js"
    ]);
    assert.ok(!fs.existsSync(path.join(target, "server")));
    assert.ok(!fs.existsSync(path.join(target, "mcp")));
    assert.ok(!fs.existsSync(path.join(target, ".git")));
    assert.ok(fs.existsSync(path.join(target, "state.html")));
    assert.equal(fs.readFileSync(path.join(target, "state.html"), "utf8"), read("state.html"));
    const editorHtml = read("state.html");
    assert.match(editorHtml, /connect-src 'self' blob: https: wss:/);
    assert.doesNotMatch(editorHtml, /script-src[^;]*'unsafe-eval'/);
    const manifest = JSON.parse(fs.readFileSync(path.join(target, "manifest.webmanifest"), "utf8"));
    const editorShortcut = manifest.shortcuts?.find(shortcut => shortcut.url === "/state.html");
    assert.ok(editorShortcut, "the installed app must expose the public editor shortcut");
    assert.ok(fs.existsSync(path.join(target, editorShortcut.url.slice(1))), "the editor shortcut target must ship");
  } finally {
    fs.rmSync(target, { recursive: true, force: true });
  }

  const unsafe = spawnSync(process.execPath, [path.join(ROOT, "scripts/stage-static-site.mjs"), "--output", ROOT], {
    cwd: ROOT,
    encoding: "utf8"
  });
  assert.notEqual(unsafe.status, 0);
  assert.match(unsafe.stderr, /Refusing unsafe static-site output directory/);

  const publicRuntime = read("index.html");
  assert.match(publicRuntime, /"actionLabel":"Editor öffnen","url":"\/state\.html"/);
  assert.doesNotMatch(publicRuntime, /"(?:url|secondaryUrl)":"[^"]*(?:studio|pilot-admin)\.html/);
  assert.doesNotMatch(publicRuntime, /state\.html[?#]/, "the public editor entry must not carry project data or tokens");
});

test("legacy branch Pages excludes repository internals as defense in depth", () => {
  const pagesConfig = read("_config.yml");
  for (const entry of [
    ".gitea",
    ".github",
    "CHANGELOG.md",
    "README.md",
    "SECURITY.md",
    "docs",
    "mcp",
    "package-lock.json",
    "package.json",
    "playwright.config.js",
    "scripts",
    "server",
    "shared",
    "statereadme.md",
    "tests"
  ]) {
    assert.match(pagesConfig, new RegExp(`^\\s*- ${entry.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&")}$`, "m"));
  }
  assert.doesNotMatch(pagesConfig, /^\s*- (?:assets|CNAME|disable-sw\.js|index\.html|manifest\.webmanifest|release-version\.js|state\.html|sw\.js)$/m);
});

test("the managed-pilot operating documents are present and explicitly non-certifying", () => {
  const requiredDocuments = [
    "docs/product/managed-pilot-v1.md",
    "docs/operations/environments.md",
    "docs/operations/release-policy.md",
    "docs/operations/production-readiness.md",
    "docs/operations/pilot-runbook.md",
    "docs/operations/incident-runbook.md",
    "docs/operations/backup-restore-runbook.md",
    "docs/operations/support-runbook.md"
  ];
  for (const relativePath of requiredDocuments) {
    assert.ok(fs.existsSync(path.join(ROOT, relativePath)), `${relativePath} is required`);
  }
  assert.match(read("docs/operations/production-readiness.md"), /keine Rechtsberatung/i);
  assert.match(read("docs/operations/production-readiness.md"), /BLOCKER/);
  assert.match(read("docs/product/managed-pilot-v1.md"), /nicht.*Self-Service/is);
});

test("generated artifacts are marked for reviewers", () => {
  const attributes = read(".gitattributes");
  assert.match(attributes, /^index\.html text eol=lf linguist-generated=true$/m);
});

test("local Markdown links in product and operating documents resolve", () => {
  const documents = [
    "README.md",
    "SECURITY.md",
    "server/README.md",
    ...fs.readdirSync(path.join(ROOT, "docs"))
      .filter(name => name.endsWith(".md"))
      .map(name => `docs/${name}`),
    ...fs.readdirSync(path.join(ROOT, "docs/product")).map(name => `docs/product/${name}`),
    ...fs.readdirSync(path.join(ROOT, "docs/operations")).map(name => `docs/operations/${name}`)
  ];
  for (const relativePath of documents) {
    const directory = path.dirname(path.join(ROOT, relativePath));
    for (const match of read(relativePath).matchAll(/\[[^\]]*\]\(([^)]+)\)/g)) {
      const target = match[1].split("#", 1)[0].trim();
      if (!target || /^(?:https?:|mailto:)/i.test(target)) continue;
      const resolved = path.resolve(directory, decodeURIComponent(target));
      assert.ok(resolved.startsWith(ROOT), `${relativePath} link escapes repository: ${target}`);
      assert.ok(fs.existsSync(resolved), `${relativePath} has a broken link: ${target}`);
    }
  }
});

function git(cwd, args) {
  const result = spawnSync("git", args, { cwd, encoding: "utf8" });
  assert.equal(result.status, 0, result.stderr || result.stdout);
  return result.stdout.trim();
}

function releaseStamp(sequence, sourceCommit) {
  return `globalThis.ZUSTAND_RELEASE_SEQUENCE = ${sequence};\n` +
    `globalThis.ZUSTAND_RELEASE_ID = "release-${sequence}";\n` +
    `globalThis.ZUSTAND_RELEASE_BUILT_AT = "2026-07-15T10:00:00Z";\n` +
    `globalThis.ZUSTAND_RELEASE_SOURCE = "${sourceCommit}";\n`;
}

function runReleasePlanner(repo, sequence, verifiedCommit) {
  const envFile = path.join(repo, "github-env.txt");
  const result = spawnSync(process.execPath, [path.join(ROOT, "scripts/plan-managed-release.mjs")], {
    cwd: repo,
    encoding: "utf8",
    env: {
      ...process.env,
      RELEASE_REPO: repo,
      REQUESTED_SEQUENCE: String(sequence),
      VERIFIED_SOURCE_COMMIT: verifiedCommit,
      GITHUB_ENV: envFile
    }
  });
  return {
    ...result,
    plan: result.status === 0 ? JSON.parse(result.stdout) : null,
    environment: fs.existsSync(envFile) ? fs.readFileSync(envFile, "utf8") : ""
  };
}

test("managed release planning resumes tag-only and main-only partial publication safely", () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "digitalisierungsplanung-release-plan-"));
  const remote = path.join(root, "origin.git");
  const repo = path.join(root, "repo");
  try {
    fs.mkdirSync(repo);
    git(root, ["init", "--bare", remote]);
    git(repo, ["init", "--initial-branch=main"]);
    git(repo, ["config", "user.name", "Release Test"]);
    git(repo, ["config", "user.email", "release@example.test"]);
    fs.writeFileSync(path.join(repo, "release-version.js"), releaseStamp(40, "0".repeat(40)));
    fs.writeFileSync(path.join(repo, "app.txt"), "verified source\n");
    git(repo, ["add", "."]);
    git(repo, ["commit", "-m", "verified source"]);
    git(repo, ["remote", "add", "origin", remote]);
    git(repo, ["push", "-u", "origin", "main"]);
    git(repo, ["fetch", "--tags", "origin", "main"]);
    const sourceCommit = git(repo, ["rev-parse", "HEAD"]);

    const fresh = runReleasePlanner(repo, 41, sourceCommit);
    assert.equal(fresh.status, 0, fresh.stderr);
    assert.equal(fresh.plan.mode, "create");
    assert.equal(fresh.plan.releaseSourceCommit, sourceCommit);
    assert.match(fresh.environment, /^RELEASE_MODE=create$/m);

    fs.writeFileSync(path.join(repo, "release-version.js"), releaseStamp(41, sourceCommit));
    git(repo, ["add", "release-version.js"]);
    git(repo, ["commit", "-m", "Release release-41"]);
    const releaseCommit = git(repo, ["rev-parse", "HEAD"]);
    git(repo, ["tag", "-a", "release-41", "-m", "release 41"]);

    // Simulate a non-atomic legacy push where only the tag reached the remote.
    git(repo, ["push", "origin", "refs/tags/release-41"]);
    git(repo, ["reset", "--hard", sourceCommit]);
    git(repo, ["fetch", "--tags", "--prune", "origin", "main"]);
    fs.rmSync(path.join(repo, "github-env.txt"), { force: true });
    const tagOnly = runReleasePlanner(repo, 41, sourceCommit);
    assert.equal(tagOnly.status, 0, tagOnly.stderr);
    assert.equal(tagOnly.plan.mode, "resume-tagged");
    assert.equal(tagOnly.plan.releaseCommit, releaseCommit);

    // Complete main, then remove the tag to model the inverse partial failure.
    git(repo, ["push", "origin", `${releaseCommit}:refs/heads/main`]);
    git(repo, ["reset", "--hard", releaseCommit]);
    git(repo, ["fetch", "origin", "main"]);
    fs.rmSync(path.join(repo, "github-env.txt"), { force: true });
    const complete = runReleasePlanner(repo, 41, releaseCommit);
    assert.equal(complete.status, 0, complete.stderr);
    assert.equal(complete.plan.mode, "resume-complete");

    git(remote, ["update-ref", "-d", "refs/tags/release-41"]);
    git(repo, ["tag", "-d", "release-41"]);
    git(repo, ["fetch", "--prune", "origin", "main"]);
    fs.rmSync(path.join(repo, "github-env.txt"), { force: true });
    const mainOnly = runReleasePlanner(repo, 41, releaseCommit);
    assert.equal(mainOnly.status, 0, mainOnly.stderr);
    assert.equal(mainOnly.plan.mode, "resume-main");
    assert.equal(mainOnly.plan.releaseCommit, releaseCommit);

    // A conflicting tag is never overwritten or silently treated as resumable.
    git(repo, ["tag", "-a", "release-41", sourceCommit, "-m", "conflict"]);
    fs.rmSync(path.join(repo, "github-env.txt"), { force: true });
    const conflict = runReleasePlanner(repo, 41, releaseCommit);
    assert.notEqual(conflict.status, 0);
    assert.match(conflict.stderr, /different commit|single stamp-only child|incompatible release stamp/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});
