import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { createServer } from "node:http";
import { extname, resolve } from "node:path";
import { createRequire } from "node:module";
import { chromium } from "playwright";

const root = resolve(process.cwd());
const canonicalExportedAt = "1970-01-01T00:00:00.000Z";
const outputFlagIndex = process.argv.indexOf("--output");
const outputPath = outputFlagIndex >= 0 && process.argv[outputFlagIndex + 1]
  ? resolve(process.cwd(), process.argv[outputFlagIndex + 1])
  : resolve(root, "index.html");
const require = createRequire(import.meta.url);
const { DEFAULT_EVENT_CATALOG } = require("../server/event-catalog");
const { productContractResponse } = require("../server/product-contract");
const contract = JSON.stringify(productContractResponse(DEFAULT_EVENT_CATALOG));
const contentTypes = {
  ".css": "text/css; charset=utf-8",
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".png": "image/png",
  ".svg": "image/svg+xml"
};
const buildServer = createServer(async (request, response) => {
  try {
    const pathname = decodeURIComponent(new URL(request.url || "/", "http://127.0.0.1").pathname);
    if (pathname === "/contract") {
      response.writeHead(200, { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" });
      response.end(contract);
      return;
    }
    const filePath = resolve(root, pathname === "/" ? "state.html" : pathname.slice(1));
    if (filePath !== root && !filePath.startsWith(root + "\\") && !filePath.startsWith(root + "/")) {
      response.writeHead(403).end();
      return;
    }
    const body = await readFile(filePath);
    response.writeHead(200, { "content-type": contentTypes[extname(filePath)] || "application/octet-stream", "cache-control": "no-store" });
    response.end(body);
  } catch (_) {
    response.writeHead(404).end();
  }
});
await new Promise((resolveListen, reject) => {
  buildServer.once("error", reject);
  buildServer.listen(0, "127.0.0.1", resolveListen);
});
const buildAddress = buildServer.address();
const buildOrigin = `http://127.0.0.1:${buildAddress.port}`;
let browser;

try {
  const executablePath = String(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH || "").trim();
  browser = await chromium.launch(executablePath ? { executablePath } : undefined);
  const context = await browser.newContext({ acceptDownloads: true, viewport: { width: 1280, height: 820 } });
  const page = await context.newPage();
  await page.goto(`${buildOrigin}/state.html?demo=zustand`, { waitUntil: "domcontentloaded" });
  await page.waitForSelector("#btnExport", { state: "visible" });
  await page.waitForSelector('[data-id="site_home"]', { state: "visible" });

  const [download] = await Promise.all([
    page.waitForEvent("download", { timeout: 10000 }),
    page.locator("#btnExport").click()
  ]);
  const downloadedPath = await download.path();
  if (!downloadedPath) throw new Error("The browser did not expose the generated index download.");

  const source = await readFile(downloadedPath, "utf8");
  const savedAtPattern = /const EXPORTED_STATE_BLUEPRINT_SAVED_AT = "[^"]*";/g;
  const savedAtMatches = source.match(savedAtPattern) || [];
  if (savedAtMatches.length !== 1) {
    throw new Error(`Expected one exported-at marker, found ${savedAtMatches.length}.`);
  }

  const normalizedBody = source
    .replace(savedAtPattern, `const EXPORTED_STATE_BLUEPRINT_SAVED_AT = "${canonicalExportedAt}";`)
    .replace(/^<!doctype html>\s*/i, "<!doctype html>\n")
    .replace(/\s*$/, "\n");
  const artifactHash = createHash("sha256").update(normalizedBody).digest("hex");
  const generatedMarker = `<!-- @generated by scripts/build-index.mjs; artifact-sha256=${artifactHash}; do not edit -->`;
  const normalized = normalizedBody.replace(/^<!doctype html>\n/i, `<!doctype html>\n${generatedMarker}\n`);
  await writeFile(outputPath, normalized, "utf8");
  await context.close();
} finally {
  if (browser) await browser.close();
  await new Promise(resolveClose => buildServer.close(resolveClose));
}
